channels:
- conda-forge
dependencies:
- python=3.11.9
- pip<=24.0
- pip:
  - mlflow==2.20.0
  - cloudpickle==3.1.1
  - feature-engine==1.8.3
  - numpy==1.26.4
  - pandas==2.2.3
  - psutil==6.1.1
  - scikit-learn==1.5.2
  - scipy==1.15.1
name: mlflow-env
